### ISSUE TITLE
Works locally but not with --adapter slack

### ISSUE THREAD

**Issue by ileathan** [hubot-archive/hubot-calculator#1]
Failed to escape HTML: TypeError: Object 2 has no method 'replace'
Slack services error: 500

**Comment by canadianveggie** [comment]
Fixed. Ensured result is a string so slack adapter can handle it.
Released as hubot-calculator 0.4.0.

**Comment by ileathan** [comment]
I confirm it is now working. Thanks canadianveggie for your contribution. I cant thank people like you enough.
